Fix math library linking causing link errors for 'gensin'
The Makefile used LDFLAGS to set "-lm" to link in the math library for
the 'sin()' function use in gensin.c.  That is wrong, and causes the
'-lm' to be too early in the implicit executable rule, resulting in
potentially undefined references at link time.

It just happened to work for me even with the wrong placement of the
linker flag.  The reason is simply that my build environment used
dynamic linking for the math library, which brings in all of libm.so
regardless of what functions you use.

A static link that only brings in the actually used functions would then
not have seen the use of 'sin()' (yet) and then the wrong placement
causes

    gensin.c: undefined reference to `sin'

Fix it by using the proper Makefile variable for the math library:
LDLIBS.

Reported-by: Max McEvoy <maxmcevoy@gmail.com>
Reported-by: Thomas <thomas.blakely@gmx.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>